name: Publish

on: workflow_dispatch

jobs:
  publish-nuget:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Restore dependencies
        working-directory: ./MinecraftServerProxy
        run: dotnet restore
        
      - name: Build
        working-directory: ./MinecraftServerProxy
        run: dotnet build --no-restore -c Release
        
      - name: Pack
        working-directory: ./MinecraftServerProxy
        run: dotnet pack --no-build -c Release
        
      - name: Push
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        working-directory: ./MinecraftServerProxy/bin/Release
        run: dotnet nuget push MinecraftServerProxy.*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
        
        
        
